types:
  poses:
    folder: res
    suffix: _poses.h5
    loader: hdf5
  video:
    folder: [dat, dat.processed]
    suffix: .mp4
    loader: video
  tracks:
    folder: res
    suffix: [_tracks_fixed.h5, _tracks.h5]
    loader: hdf5
  

loaders:
  hdf5:
    extensions: [h5, hdf, hdf5]
    module: deepdish
    function: io.load
  video:
    extensions: [mp4, avi]
    module: videoreader
    function: VideoReader
  npy:
    extensions: [npy, npz]
    module: numpy
    function: load
  csv:
    extensions: [csv]
    module: pandas
    function: from_csv
    # args: [arguments]
    # kwargs: {Delimiter: \t}
